version: '3.8'

services:
  # Auth Service
  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    container_name: quizzer-auth
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=${AUTH_SERVICE_PORT}
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    networks:
      - quizzer-network

  # AI Service
  ai-service:
    build:
      context: .
      dockerfile: services/ai-service/Dockerfile
    container_name: quizzer-ai
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=${AI_SERVICE_PORT}
      - AUTH_SERVICE_URL=http://auth-service:${AUTH_SERVICE_PORT}
    ports:
      - "${AI_SERVICE_PORT}:${AI_SERVICE_PORT}"
    depends_on:
      - auth-service
    networks:
      - quizzer-network

  # Quiz Service
  quiz-service:
    build:
      context: .
      dockerfile: services/quiz-service/Dockerfile
    container_name: quizzer-quiz
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=${QUIZ_SERVICE_PORT}
      - AUTH_SERVICE_URL=http://auth-service:${AUTH_SERVICE_PORT}
      - AI_SERVICE_URL=http://ai-service:${AI_SERVICE_PORT}
    ports:
      - "${QUIZ_SERVICE_PORT}:${QUIZ_SERVICE_PORT}"
    depends_on:
      - auth-service
      - ai-service
    networks:
      - quizzer-network

  # Analytics Service
  analytics-service:
    build:
      context: .
      dockerfile: services/analytics-service/Dockerfile
    container_name: quizzer-analytics
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=${ANALYTICS_SERVICE_PORT}
      - AUTH_SERVICE_URL=http://auth-service:${AUTH_SERVICE_PORT}
      - QUIZ_SERVICE_URL=http://quiz-service:${QUIZ_SERVICE_PORT}
    ports:
      - "${ANALYTICS_SERVICE_PORT}:${ANALYTICS_SERVICE_PORT}"
    depends_on:
      - auth-service
      - quiz-service
    networks:
      - quizzer-network

  # Submission Service
  submission-service:
    build:
      context: .
      dockerfile: services/submission-service/Dockerfile
    container_name: quizzer-submission
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=${SUBMISSION_SERVICE_PORT}
      - AUTH_SERVICE_URL=http://auth-service:${AUTH_SERVICE_PORT}
      - QUIZ_SERVICE_URL=http://quiz-service:${QUIZ_SERVICE_PORT}
      - AI_SERVICE_URL=http://ai-service:${AI_SERVICE_PORT}
      - ANALYTICS_SERVICE_URL=http://analytics-service:${ANALYTICS_SERVICE_PORT}
    ports:
      - "${SUBMISSION_SERVICE_PORT}:${SUBMISSION_SERVICE_PORT}"
    depends_on:
      - auth-service
      - quiz-service
      - ai-service
      - analytics-service
    networks:
      - quizzer-network

networks:
  quizzer-network:
    driver: bridge
