name: quizzer

services:
  auth:
    build:
      context: ./services/auth-service
      target: builder
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - HOST=${HOST:-0.0.0.0}
    env_file:
      - services/auth-service/.env
    command: yarn dev
    volumes:
      - ./services/auth-service:/app
      - auth_node_modules:/app/node_modules
    restart: unless-stopped

  quiz:
    build:
      context: ./services/quiz-service
      target: builder
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - HOST=${HOST:-0.0.0.0}
    env_file:
      - services/quiz-service/.env
    command: yarn dev
    volumes:
      - ./services/quiz-service:/app
      - quiz_node_modules:/app/node_modules
    restart: unless-stopped

  ai:
    build:
      context: ./services/ai-service
      target: builder
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - HOST=${HOST:-0.0.0.0}
    env_file:
      - services/ai-service/.env
    command: yarn dev
    volumes:
      - ./services/ai-service:/app
      - ai_node_modules:/app/node_modules
    restart: unless-stopped

  submission:
    build:
      context: ./services/submission-service
      target: builder
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - HOST=${HOST:-0.0.0.0}
    env_file:
      - services/submission-service/.env
    command: yarn dev
    volumes:
      - ./services/submission-service:/app
      - submission_node_modules:/app/node_modules
    restart: unless-stopped

  analytics:
    build:
      context: ./services/analytics-service
      target: builder
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - HOST=${HOST:-0.0.0.0}
    env_file:
      - services/analytics-service/.env
    command: yarn dev
    volumes:
      - ./services/analytics-service:/app
      - analytics_node_modules:/app/node_modules
    restart: unless-stopped

volumes:
  auth_node_modules:
  quiz_node_modules:
  ai_node_modules:
  submission_node_modules:
  analytics_node_modules: