name: ci-cd-azure-container-apps

on:
  push:
    branches: [ microservices ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  RG: ${{ secrets.AZURE_RESOURCE_GROUP }}
  ENV_NAME: ${{ secrets.AZURE_CONTAINERAPPS_ENV }}
  LOCATION: ${{ secrets.AZURE_LOCATION }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Normalize owner to lowercase
        run: echo "OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate .env files for all services (for parity; runtime uses env vars)
        shell: bash
        run: |
          set -e
          mkdir -p services/auth-service services/quiz-service services/ai-service services/submission-service services/analytics-service
          cat > services/auth-service/.env <<'EOF'
          NODE_ENV=production
          AUTH_SERVICE_PORT=3001
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          EOF
          cat > services/quiz-service/.env <<'EOF'
          NODE_ENV=production
          QUIZ_SERVICE_PORT=3002
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          EOF
          cat > services/ai-service/.env <<'EOF'
          NODE_ENV=production
          AI_SERVICE_PORT=3003
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
          GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}
          EOF
          cat > services/submission-service/.env <<'EOF'
          NODE_ENV=production
          SUBMISSION_SERVICE_PORT=3004
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          EOF
          cat > services/analytics-service/.env <<'EOF'
          NODE_ENV=production
          ANALYTICS_SERVICE_PORT=3005
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          EOF

      - name: Build and push auth-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./services/auth-service/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/quizzer-auth-service:${{ github.sha }}
            ghcr.io/${{ env.OWNER_LC }}/quizzer-auth-service:latest

      - name: Build and push quiz-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./services/quiz-service/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/quizzer-quiz-service:${{ github.sha }}
            ghcr.io/${{ env.OWNER_LC }}/quizzer-quiz-service:latest

      - name: Build and push ai-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./services/ai-service/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/quizzer-ai-service:${{ github.sha }}
            ghcr.io/${{ env.OWNER_LC }}/quizzer-ai-service:latest

      - name: Build and push submission-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./services/submission-service/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/quizzer-submission-service:${{ github.sha }}
            ghcr.io/${{ env.OWNER_LC }}/quizzer-submission-service:latest

      - name: Build and push analytics-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./services/analytics-service/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/quizzer-analytics-service:${{ github.sha }}
            ghcr.io/${{ env.OWNER_LC }}/quizzer-analytics-service:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI - Ensure Container Apps extension
        uses: azure/cli@v2
        with:
          inlineScript: |
            set -e
            az extension add --name containerapp --upgrade
            az provider register --namespace Microsoft.App --wait

      - name: Create Resource Group and Container Apps Environment (idempotent)
        uses: azure/cli@v2
        with:
          inlineScript: |
            set -e
            az group create -n "$RG" -l "$LOCATION"
            if ! az containerapp env show -n "$ENV_NAME" -g "$RG" >/dev/null 2>&1; then
              az containerapp env create -n "$ENV_NAME" -g "$RG" -l "$LOCATION" --logs-destination none
            fi

      - name: Deploy/Update services to Azure Container Apps
        uses: azure/cli@v2
        with:
          inlineScript: |
            set -e
            REGISTRY_SERVER=ghcr.io
            REGISTRY_USER=${{ secrets.GHCR_USERNAME }}
            REGISTRY_PASS='${{ secrets.GHCR_TOKEN }}'
            OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

            upsert_app() {
              APP_NAME=$1
              IMAGE=$2
              PORT=$3
              SECRETS=$4           # k1='v1' k2='v2'
              ENV_PLAIN=$5         # KEY=VALUE KEY2=VALUE2
              ENV_SECRET_REFS=$6   # KEY=secretref:name KEY2=secretref:name

              if az containerapp show -n "$APP_NAME" -g "$RG" >/dev/null 2>&1; then
                if [ -n "$SECRETS" ]; then
                  az containerapp secret set -n "$APP_NAME" -g "$RG" --secrets $SECRETS
                fi
                az containerapp update \
                  -n "$APP_NAME" -g "$RG" \
                  --image "$IMAGE" \
                  --registry-server $REGISTRY_SERVER \
                  --registry-username "$REGISTRY_USER" \
                  --registry-password "$REGISTRY_PASS" \
                  --target-port $PORT \
                  --ingress external \
                  --env-vars $ENV_PLAIN $ENV_SECRET_REFS
              else
                az containerapp create \
                  -n "$APP_NAME" -g "$RG" \
                  --environment "$ENV_NAME" \
                  --image "$IMAGE" \
                  --registry-server $REGISTRY_SERVER \
                  --registry-username "$REGISTRY_USER" \
                  --registry-password "$REGISTRY_PASS" \
                  --target-port $PORT \
                  --ingress external \
                  --min-replicas 0 --max-replicas 1 \
                  --secrets $SECRETS \
                  --env-vars $ENV_PLAIN $ENV_SECRET_REFS
              fi
            }

            # auth-service
            upsert_app \
              quizzer-auth-service \
              ghcr.io/$OWNER_LC/quizzer-auth-service:${{ github.sha }} \
              3001 \
              "mongodb-uri='${{ secrets.MONGODB_URI }}' jwt-secret='${{ secrets.JWT_SECRET }}'" \
              "NODE_ENV=production AUTH_SERVICE_PORT=3001" \
              "MONGODB_URI=secretref:mongodb-uri JWT_SECRET=secretref:jwt-secret"

            # quiz-service
            upsert_app \
              quizzer-quiz-service \
              ghcr.io/$OWNER_LC/quizzer-quiz-service:${{ github.sha }} \
              3002 \
              "mongodb-uri='${{ secrets.MONGODB_URI }}'" \
              "NODE_ENV=production QUIZ_SERVICE_PORT=3002" \
              "MONGODB_URI=secretref:mongodb-uri"

            # ai-service
            upsert_app \
              quizzer-ai-service \
              ghcr.io/$OWNER_LC/quizzer-ai-service:${{ github.sha }} \
              3003 \
              "mongodb-uri='${{ secrets.MONGODB_URI }}' gemini-api-key='${{ secrets.GEMINI_API_KEY }}' groq-api-key='${{ secrets.GROQ_API_KEY }}'" \
              "NODE_ENV=production AI_SERVICE_PORT=3003" \
              "MONGODB_URI=secretref:mongodb-uri GEMINI_API_KEY=secretref:gemini-api-key GROQ_API_KEY=secretref:groq-api-key"

            # submission-service
            upsert_app \
              quizzer-submission-service \
              ghcr.io/$OWNER_LC/quizzer-submission-service:${{ github.sha }} \
              3004 \
              "mongodb-uri='${{ secrets.MONGODB_URI }}'" \
              "NODE_ENV=production SUBMISSION_SERVICE_PORT=3004" \
              "MONGODB_URI=secretref:mongodb-uri"

            # analytics-service
            upsert_app \
              quizzer-analytics-service \
              ghcr.io/$OWNER_LC/quizzer-analytics-service:${{ github.sha }} \
              3005 \
              "mongodb-uri='${{ secrets.MONGODB_URI }}'" \
              "NODE_ENV=production ANALYTICS_SERVICE_PORT=3005" \
              "MONGODB_URI=secretref:mongodb-uri"
