name: Deploy to Azure Container Instances

on:
  push:
    branches: [ microservices ]
  pull_request:
    branches: [ microservices ]

env:
  AZURE_RESOURCE_GROUP: quizzer-rg
  AZURE_LOCATION: eastus
  CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY_NAME }}
  IMAGE_TAG: ${{ github.sha }}
  WEBAPP_PLAN: quizzer-free-plan
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Build all services
      run: yarn build
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Login to Azure Container Registry
      run: |
        az acr login --name ${{ env.CONTAINER_REGISTRY }}
        
    - name: Build and push AI Service image
      run: |
        docker build -t ${{ env.CONTAINER_REGISTRY }}.azurecr.io/ai-service:${{ env.IMAGE_TAG }} \
          -f services/ai-service/Dockerfile services/ai-service
        docker push ${{ env.CONTAINER_REGISTRY }}.azurecr.io/ai-service:${{ env.IMAGE_TAG }}
        
    - name: Build and push Analytics Service image
      run: |
        docker build -t ${{ env.CONTAINER_REGISTRY }}.azurecr.io/analytics-service:${{ env.IMAGE_TAG }} \
          -f services/analytics-service/Dockerfile services/analytics-service
        docker push ${{ env.CONTAINER_REGISTRY }}.azurecr.io/analytics-service:${{ env.IMAGE_TAG }}
        
    - name: Build and push Auth Service image
      run: |
        docker build -t ${{ env.CONTAINER_REGISTRY }}.azurecr.io/auth-service:${{ env.IMAGE_TAG }} \
          -f services/auth-service/Dockerfile services/auth-service
        docker push ${{ env.CONTAINER_REGISTRY }}.azurecr.io/auth-service:${{ env.IMAGE_TAG }}
        
    - name: Build and push Quiz Service image
      run: |
        docker build -t ${{ env.CONTAINER_REGISTRY }}.azurecr.io/quiz-service:${{ env.IMAGE_TAG }} \
          -f services/quiz-service/Dockerfile services/quiz-service
        docker push ${{ env.CONTAINER_REGISTRY }}.azurecr.io/quiz-service:${{ env.IMAGE_TAG }}
        
    - name: Build and push Submission Service image
      run: |
        docker build -t ${{ env.CONTAINER_REGISTRY }}.azurecr.io/submission-service:${{ env.IMAGE_TAG }} \
          -f services/submission-service/Dockerfile services/submission-service
        docker push ${{ env.CONTAINER_REGISTRY }}.azurecr.io/submission-service:${{ env.IMAGE_TAG }}
        
    - name: Deploy AI Service to Azure Container Instances
      run: |
        az container create \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name ai-service \
          --image ${{ env.CONTAINER_REGISTRY }}.azurecr.io/ai-service:${{ env.IMAGE_TAG }} \
          --registry-login-server ${{ env.CONTAINER_REGISTRY }}.azurecr.io \
          --registry-username ${{ secrets.REGISTRY_USERNAME }} \
          --registry-password ${{ secrets.REGISTRY_PASSWORD }} \
          --ports 3001 \
          --cpu 0.5 \
          --memory 1 \
          --environment-variables NODE_ENV=production PORT=3001 \
          --restart-policy OnFailure
          
    - name: Deploy Analytics Service to Azure Container Instances
      run: |
        az container create \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name analytics-service \
          --image ${{ env.CONTAINER_REGISTRY }}.azurecr.io/analytics-service:${{ env.IMAGE_TAG }} \
          --registry-login-server ${{ env.CONTAINER_REGISTRY }}.azurecr.io \
          --registry-username ${{ secrets.REGISTRY_USERNAME }} \
          --registry-password ${{ secrets.REGISTRY_PASSWORD }} \
          --ports 3002 \
          --cpu 0.5 \
          --memory 1 \
          --environment-variables NODE_ENV=production PORT=3002 \
          --restart-policy OnFailure
          
    - name: Deploy Auth Service to Azure Container Instances
      run: |
        az container create \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name auth-service \
          --image ${{ env.CONTAINER_REGISTRY }}.azurecr.io/auth-service:${{ env.IMAGE_TAG }} \
          --registry-login-server ${{ env.CONTAINER_REGISTRY }}.azurecr.io \
          --registry-username ${{ secrets.REGISTRY_USERNAME }} \
          --registry-password ${{ secrets.REGISTRY_PASSWORD }} \
          --ports 3003 \
          --cpu 0.5 \
          --memory 1 \
          --environment-variables NODE_ENV=production PORT=3003 \
          --restart-policy OnFailure
          
    - name: Deploy Quiz Service to Azure Container Instances
      run: |
        az container create \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name quiz-service \
          --image ${{ env.CONTAINER_REGISTRY }}.azurecr.io/quiz-service:${{ env.IMAGE_TAG }} \
          --registry-login-server ${{ env.CONTAINER_REGISTRY }}.azurecr.io \
          --registry-username ${{ secrets.REGISTRY_USERNAME }} \
          --registry-password ${{ secrets.REGISTRY_PASSWORD }} \
          --ports 3004 \
          --cpu 0.5 \
          --memory 1 \
          --environment-variables NODE_ENV=production PORT=3004 \
          --restart-policy OnFailure
          
    - name: Deploy Submission Service to Azure Container Instances
      run: |
        az container create \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name submission-service \
          --image ${{ env.CONTAINER_REGISTRY }}.azurecr.io/submission-service:${{ env.IMAGE_TAG }} \
          --registry-login-server ${{ env.CONTAINER_REGISTRY }}.azurecr.io \
          --registry-username ${{ secrets.REGISTRY_USERNAME }} \
          --registry-password ${{ secrets.REGISTRY_PASSWORD }} \
          --ports 3005 \
          --cpu 0.5 \
          --memory 1 \
          --environment-variables NODE_ENV=production PORT=3005 \
          --restart-policy OnFailure